### ISSUE TITLE
cardano-container-mainnet availability

### ISSUE THREAD

**Issue by darkverbito** [vacuumlabs/adalite-backend-service#44]
Tried using `docker-compose -p ada_lite up --build -d` but got the following error:

```
Pulling icarus-importer (cardano-container-mainnet:)...
ERROR: pull access denied for cardano-container-mainnet, repository does not exist or may require 'docker login'
```

Is `cardano-container-mainnet` available for use?

**Comment by refi93** [comment]
sorry, this container is not publicly available, but it is fixed in PR #42 which will be merged soon, but you can use it already. See readme for updated instructions on how to launch the server. We added there a shell script to conveniently build and launch the containers and updated docker-compose to use publicly available images only, i.e. we publicly hosted that container (indeed the same one, but hosted on docker hub) but it is named differently in docker hub (https://cloud.docker.com/u/refi93/repository/docker/refi93/project-icarus-importer).

Please bear in mind, this container won't survive the OBFT switch (date unknown, see Cardano newsletter: https://iohk.zendesk.com/hc/en-us/articles/360025445614-Newsletter-25th-June-2019-Cardano-1-5-2-with-Cardano-SL-3-0-2-released). We are waiting for a replacement for it from Emurgo/IOHK, and we will update this repo accordingly then.

**Comment by ksemaev** [comment]
@refi93 TY for explaining! I found the image https://hub.docker.com/r/refi93/project-icarus-importer but can you please share dockerfile? I did manage to start importer, but it doesn't listen on any port. Maybe you can advice some missing cli options for me? 

I currently start it with something like:
`cardano-blockchain-importer  --configuration-file $CONFIG_DIR/configuration.yaml --configuration-key mainnet_full --log-config $CONFIG_DIR/log-config-connect-to-cluster.yaml --topology $CONFIG_DIR/topology.yaml`

Maybe you can share configfile with api port enabled?

**Comment by ksemaev** [comment]
@refi93 also is you image from https://github.com/input-output-hk/cardano-sl or is it some hacked https://github.com/input-output-hk/project-icarus-importer ?

**Comment by refi93** [comment]
@ksemaev here is the docker compose file which uses cardano-blockchain-importer: https://github.com/vacuumlabs/adalite-backend-service/blob/refactor-docker-env/docker/docker-compose.yml. I recommend you to use it via the shellscript included in the same folder to load the proper environment variables.

here is a sample .env file you can use and would expose the service on port 8080 on your host machine, you should name it `<some_name>.env` and provide that name to the `manage_containers.sh` shellscript in order for it to pick it up, as explained in the readme:

```
ADALITE_BACKEND_HOST_PORT=8080
ICARUS_IMPORTER_HOST_PORT=8200
DB_HOST_PORT=5431
DATA_PATH=/some/path/to/folder

SLACK_TOKEN=
SLACK_CHANNEL=
POSTGRES_PASSWORD=passs
CORS_ENABLED_FOR="*"
```

`cardano-blockchain-importer` is built directly from `project-icarus-importer`, and can be built with
```
docker load -i "$(nix-build importer/ -A dockerImages.mainnetBlockchainImporter --argstr gitrev "undefined" --no-out-link)"
```
when executed in the root folder of https://github.com/input-output-hk/project-icarus-importer and can be executed with this command (with slight modifications, depending on your usecase): https://github.com/vacuumlabs/adalite-backend-service/blob/976545849eb120502b78394706f31caa9a77d4d4/docker/docker-compose.yml#L32
But you should not need to build that image yourself since it is hosted on docker hub - the `project-icarus-importer` will be discontinued anyway after the OBFT switch

**Comment by ksemaev** [comment]
@refi93 TY for explaining. I just need to have alpine images, to have some custom scripts and tools working in container for my kuber env. Anyway is seems like I managed to do it.

**Comment by ksemaev** [comment]
@darkverbito please close the issue, the container is avaliable https://hub.docker.com/r/refi93/project-icarus-importer
