### ISSUE TITLE
Healthcheck api call returnes unhealthy

### ISSUE THREAD

**Issue by ksemaev** [vacuumlabs/adalite-backend-service#47]
API call `api/v2/healthcheck` keeps returning ""The instance is unhealthy", while all other api calls are working.

Can you please explain what is it checking exactly?

**Comment by refi93** [comment]
here is the code: https://github.com/vacuumlabs/adalite-backend-service/blob/refactor-docker-env/src/healthcheck.js - it basically checks if the database is not stale (the importer stopped syncing) and if we are able to submit transactions. If the healthcheck fails, the endpoints are not turned off right away but after 50 seconds https://github.com/vacuumlabs/adalite-backend-service/blob/976545849eb120502b78394706f31caa9a77d4d4/src/middleware/response-guard.js#L15 to give time to the load balancer on top of the backend service to pick up the healthcheck result and gracefully stop routing to the instance without returning error 500 to the users.

**Comment by ksemaev** [comment]
@refi93 I checked - importer is syncing, as `api/v2/bestBlock` coninues to grow, but healthcheck still reports unhealthy.
Can you please advice on how to check if submitting of transcations working?

**Comment by refi93** [comment]
one option is to wait all the way until the instance synces which may take very long so I guess that's not an option for you. The other is disabling the healthcheck by hardcoding there some condition that is true. We don't have a flag in .env for disabling the healthcheck, sadly, since for development we were connecting to a synced db, but feel free to submit a PR

**Comment by ksemaev** [comment]
I will wait for ful sync, NP! But can you advice how is bestblockmber (which is some number) related to the blockheight (which is epochs and slots)? I can't understand how to calculate the latest block :(

**Comment by refi93** [comment]
A slot lasts 20 seconds and an epoch is 21600 slots (source: https://github.com/input-output-hk/cardano-sl/blob/master/scripts/prepare-genesis/README.md and https://cardanodocs.com/technical/) since `slotDuration` is 20000 ms and `k` is 2160 in the genesis JSON.

BestBlock is the number of blocks (slots) elapsed from the beginning, so it is `currentEpoch * 21600 + currentSlot`

**Comment by refi93** [comment]
A slot lasts 20 seconds and an epoch is 21600 slots (source: https://github.com/input-output-hk/cardano-sl/blob/master/scripts/prepare-genesis/README.md and https://cardanodocs.com/technical/) since slotDuration is 20000 ms and k is 2160 in the genesis JSON. A block can be issued during a slot, but not necessarily (e.g. the slot leader can be offline, see the docs referenced above), so the number of slots is only loosely related to the actual number of blocks.

You are probably asking about transaction's `ctsBlockHeight` probably https://github.com/vacuumlabs/adalite-backend-service/blob/ad34517b831df6742708d8a5b343fb6f8fe0eba2/src/legacy-routes.js#L98

And as you can notice, `ctsBlockEpoch * 21600 + ctsBlockSlot` do not exactly add up to `ctsBlockHeight`. So now I'm realizing that our healthcheck logic for checking the expected bestBlock is not right since it tries to determine the block number from the time - I will create an issue for that, thanks for raising this!

Currently this is only a theoretical problem since the nodes that create blocks are still being controlled by IOHK, so the current offset was probably caused by some early downtime of the network and seems not to be changing.
