### ISSUE TITLE
Allow migrations script not to fail if already done the job

### ISSUE THREAD

**Issue by ksemaev** [vacuumlabs/adalite-backend-service#49]
Currently the line `arn knex migrate:latest` in start command outputs error with something like `already exists` (Can't reproduce at the moment, as infra is in sync).

Can we make this script pass with no errors, if the migrations were already done by previous runs?

**Comment by refi93** [comment]
Perhaps you initialized the database structure by running directly the project-icarus-importer container which would clash with knex, since there wouldn't be the auxiliary table to keep track of migrations. I think the default command of the container runs this shellscript: https://github.com/input-output-hk/project-icarus-importer/blob/248c7880c25e641c78a620e3a3f97149e98eeb93/scripts/generate/blockImporterTables-beta.sql

Currently the order is ensured by the docker-compose file and the default command of the project-icarus-importer container is overriden with one that does not involve running the shellscript to initialize the db.

This setup will change soon anyway since we will be plugging in a different service to import the blockchain.
