### ISSUE TITLE
how to start a testnet ada by docker-compose

### ISSUE THREAD

**Issue by garysdevil** [vacuumlabs/adalite-backend-service#71]
If I want to deploy a testnet, which branch should I clone? And how to config the .env?
I set CARDANO_NETWORK=testnet, but I deployed fail.

**Comment by refi93** [comment]
@garysdevil You should use the branch new-importer, but we were actually testing it only with mainnet as far as I know, even if it is possible to specify other network in the `CARDANO_NETWORK` parameter, e.g. testnet.

What steps did you take and what kind of error are you getting when you try to launch adalite-backend-service as testnet node?

**Comment by xdzurman** [comment]
@garysdevil If you meant **_shelley (incentivized) testnet_**, do this:

You have to properly set up Tangata Manu Importer (https://github.com/Emurgo/tangata-manu/tree/master-shelley) on the master-shelley branch. I'll outline the commands I used to possibly save you some time.

**Install LFS (used later for migrations)**

wget https://github.com/git-lfs/git-lfs/releases/download/v2.9.1/git-lfs-linux-amd64-v2.9.1.tar.gz
tar xzvf git-lfs-linux-amd64-v2.9.1.tar.gz
chmod +x install.sh

**Clone repo**

git clone --recursive git@github.com:Emurgo/tangata-manu.git -b master-shelley --single-branch

**Create database**

docker pull postgres:11.2;
docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres;
docker exec -it postgres psql -U postgres;
create database yoroi_blockchain_importer;

**You have to update tangata submodules (if you are not doing this locally and you do not use github credentials there, you have to edit .gitmodules file and change urls to http instead of git ssh) by following commands:**

git submodule sync
git submodule init
git submodule update --init --recursive

**Now you build js-chain-libs:**

cd js-chain-libs
git submodule init
git submodule update
wasm-pack build
wasm-pack pack

**And install dependencies**

cd ..
yarn run migrate-shelley up
yarn install

**Edit config/default.json so that "port" in "server" is the one you wish to use for the importer and "defaultBridgeUrl" is a link to REST port of your jormungandr node. "defaultNetwork" should be "itn-rewards-v1" for incentivized testnet.**

yarn run dev (if this runs, you have tangata manu set up)

Next, pull "testnet" branch of adalite-backend-service. Build it and .env should look like this:

DB=yoroi_blockchain_importer
DB_USER=postgres
DB_PASSWORD=mysecretpassword
DB_HOST=localhost
DB_PORT=5432
PORT=<port-you-wish-backend-to-run-on>
IMPORTER_ENDPOINT=http://<where-your-tangata-runs>:<port-specified-in-tangata-default.json>/api/txs/signed
SLACK_TOKEN=
SLACK_CHANNEL=
CORS_ENABLED_FOR=http://*,https://*
JORMUN_NODE=http://<url-to-jormun-node>:<jormun-node-port>

**With tangata manu running, also start adalite-backend-service by**
yarn run dev

**Comment by garysdevil** [comment]
> @garysdevil You should use the branch new-importer, but we were actually testing it only with mainnet as far as I know, even if it is possible to specify other network in the `CARDANO_NETWORK` parameter, e.g. testnet.
> 
> What steps did you take and what kind of error are you getting when you try to launch adalite-backend-service as testnet node?

I chose "shelley-testnet, testnet ,develop"  branches to run testnet, CARDANO_NETWORK=testnet, but I failed.  
So you deposit or withdraw in mannet directly when you develop an app to invokes RPC?
Anyway, thank you

**Comment by garysdevil** [comment]
> @garysdevil If you meant **_shelley (incentivized) testnet_**, do this:
> 
> You have to properly set up Tangata Manu Importer (https://github.com/Emurgo/tangata-manu/tree/master-shelley) on the master-shelley branch. I'll outline the commands I used to possibly save you some time.
> 
> **Install LFS (used later for migrations)**
> 
> wget https://github.com/git-lfs/git-lfs/releases/download/v2.9.1/git-lfs-linux-amd64-v2.9.1.tar.gz
> tar xzvf git-lfs-linux-amd64-v2.9.1.tar.gz
> chmod +x install.sh
> 
> **Clone repo**
> 
> git clone --recursive [git@github.com](mailto:git@github.com):Emurgo/tangata-manu.git
> 
> **Create database**
> 
> docker pull postgres:11.2;
> docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres;
> docker exec -it postgres psql -U postgres;
> create database yoroi_blockchain_importer;
> 
> **You have to update tangata submodules (if you are not doing this locally and you do not use github credentials there, you have to edit .gitmodules file and change urls to http instead of git ssh) by following commands:**
> 
> git submodule sync
> git submodule init
> git submodule update --init --recursive
> 
> **Now you build js-chain-libs:**
> 
> cd js-chain-libs
> git submodule init
> git submodule update
> wasm-pack build
> wasm-pack pack
> 
> **And install dependencies**
> 
> cd ..
> yarn run migrate-shelley up
> yarn install
> 
> **Edit config/default.json so that "port" in "server" is the one you wish to use for the importer and "defaultBridgeUrl" is a link to REST port of your jormungandr node. "defaultNetwork" should be "itn-rewards-v1" for incentivized testnet.**
> 
> yarn run dev (if this runs, you have tangata manu set up)
> 
> Next, pull "testnet" branch of adalite-backend-service. Build it and .env should look like this:
> 
> DB=yoroi_blockchain_importer
> DB_USER=postgres
> DB_PASSWORD=mysecretpassword
> DB_HOST=localhost
> DB_PORT=5432
> PORT=
> IMPORTER_ENDPOINT=http://:<port-specified-in-tangata-default.json>/api/txs/signed
> SLACK_TOKEN=
> SLACK_CHANNEL=
> CORS_ENABLED_FOR=http://_,https://_
> JORMUN_NODE=http://:
> 
> **With tangata manu running, also start adalite-backend-service by**
> yarn run dev

It seems to be completed, but thank you!
